Feature/teams
forj-oss/forjj-bitbucket pull request #6
Opened 2018-10-16 07:29 UTC by Xx-Parks-xX

2018-10-16 07:58 UTC, clarsonneur commented
Is it a work in progress, or you are ready to merge it?

2018-10-16 08:06 UTC, clarsonneur requested changes
Several reference to gitlab to update

I guess, the code is still in progress. Think to add/update your README.md to any extra information, if needed.

2018-10-16 08:06 UTC, clarsonneur commented on bitbucket.yaml
> +        help: true (default) to ask gitlab to verify the SSL.
gitlab  => bitbucket

2018-10-16 08:06 UTC, clarsonneur commented on generated-yaml-structs.go
>  	Team string `json:"team"` // Gitlab group name.
Some other reference to gitlab which needs to be replaced

2018-10-16 08:06 UTC, clarsonneur commented on generated-yaml-structs.go
>  	ForjjTeam string `json:"forjj-team"` // Default FORJJ group. Used by default as gitlab group. If you want different one, use --gitlab-group
gitlab

2018-10-16 08:06 UTC, clarsonneur commented on generated-yaml-structs.go
> +	SslCheck string `json:"ssl-check"` // true (default) to ask gitlab to verify the SSL.
gitlab

2018-10-16 08:06 UTC, clarsonneur commented on generated-yaml-structs.go
> +   "        help: true (default) to ask gitlab to verify the SSL.\n" +
another gitlab

2018-10-16 08:06 UTC, clarsonneur commented on bitbucket_plugin.go
> +	Repos                 map[string]RepositoryStruct // projects managed in gitlab
gitlab

2018-10-17 07:14 UTC, Xx-Parks-xX commented
The code has been cleaned, the branch can be merged.

2018-10-17 12:39 UTC, merged